services:
    notify.producer.toastr:
        parent: 'notify.producer.abstract'
        class: Notify\Toastr\Producer\ToastrProducer
        tags:
            - { name: 'notify.producer', alias: 'toastr' }

    notify.renderer.toastr:
        class: Notify\Toastr\Renderer\ToastrRenderer
        arguments:
            - '@notify.config'
        tags:
            - { name: 'notify.renderer', alias: 'toastr' }

    Notify\Toastr\Producer\ToastrProducer: '@notify.producer.toastr'
    Notify\Toastr\Renderer\ToastrRenderer: '@notify.renderer.toastr'
